name: caret-version

# on:
#   push:
#     tags:
#       - 'refs/taro-yu/Caret:v\d\.\d\.\d'
    
  
on:
  repository_dispatch:
    types: [created]
    repo: taro-yu/Caret


jobs:
  caret-version:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/taro-yu/Caret/tags | jq -r .[0].name)
          echo "Latest Caret tag: $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"
      
      
      - name: Set up Git
        run: |
          git config --global user.email "milktea1621@gmail.com"
          git config --global user.name "yu-taro-"
                  

      - name: Checkout ros2cmd 
        uses: actions/checkout@v3
        with:
          repository: taro-yu/ros2cmd
          ref: main


      - name: Update version in setup.py
        run: |
          latest_tag=${{ steps.get_tag.outputs.latest_tag }}
          sed -i "s/version=.*/version='$latest_tag',/" setup.py
          git add setup.py
          git commit -m "Update version to $latest_tag" 
          git push origin main
     
